{
 "title": "Bitcoin",
 "tags": [ "bitcoin" ],
 "time": { "from": "now/w", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(bitcoin_uptime, instance)"
    }
   },
   {
    "name": "chain",
    "query": {
     "query": "label_values(bitcoin_uptime, chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up time",
   "type": "stat",
   "description": "Up time without interuption",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_uptime{instance=~'$instance'}",
     "legendFormat": "{{instance}} - {{chain}} - {{version}} - {{protocol}}"
    }
   ]
  },
  {
   "title": "Node information",
   "type": "table",
   "description": "bitcoin core information and on which chain they are operating",
   "gridPos": { "h": 7, "w": 11, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "bitcoin_uptime{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Network Hash Rate",
   "type": "timeseries",
   "description": "Estimated network hashes per second",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "avg(bitcoin_hashps)", "legendFormat": "120-blocks" },
    { "expr": "avg(bitcoin_hashps_neg1)", "legendFormat": "last-difficulty" }
   ]
  },
  {
   "title": "Difficulty",
   "type": "timeseries",
   "description": "Difficulty value",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "avg(bitcoin_difficulty)", "legendFormat": "difficulty" }
   ]
  },
  {
   "title": "Block Creation Rate",
   "type": "timeseries",
   "description": "Number of blocks created per day using different trailing rates.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(sum(rate(bitcoin_blocks[3h])) * 3600 * 24)",
     "legendFormat": "3h"
    },
    {
     "expr": "floor(sum(rate(bitcoin_blocks[6h])) * 3600 * 24)",
     "legendFormat": "6h"
    },
    {
     "expr": "floor(sum(rate(bitcoin_blocks[12h])) * 3600 * 24)",
     "legendFormat": "12h"
    },
    {
     "expr": "floor(sum(rate(bitcoin_blocks[7d])) * 3600 * 24)",
     "legendFormat": "7d"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "Sent and received traffic rates",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(bitcoin_total_bytes_sent[5m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "-sum(irate(bitcoin_total_bytes_recv[10m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Estimated Fee",
   "type": "timeseries",
   "description": "The estimated smart fee for confirmation of transactions in a given number of blocks.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "avg(bitcoin_est_smart_fee_2)", "legendFormat": "2-blocks" },
    { "expr": "avg(bitcoin_est_smart_fee_20)", "legendFormat": "20-blocks" },
    { "expr": "avg(bitcoin_est_smart_fee_3)", "legendFormat": "3-blocks" },
    { "expr": "avg(bitcoin_est_smart_fee_5)", "legendFormat": "5-blocks" }
   ]
  },
  {
   "title": "Block value",
   "type": "timeseries",
   "description": "Value of the block transactions in BTC.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(bitcoin_latest_block_value)",
     "legendFormat": "BTC"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "description": "Number of peers that have been banned and the reason for the ban.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(bitcoin_banned_until) by (reason)",
     "legendFormat": "ban - {{ reason }}"
    },
    { "expr": "sum(bitcoin_peers)", "legendFormat": "peers" }
   ]
  },
  {
   "title": "Chain Branches",
   "type": "timeseries",
   "description": "Number of tips seen in the chain.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "avg(bitcoin_num_chaintips)", "legendFormat": "tips" }
   ]
  }
 ]
}